name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        name: Isometric calendar (dark)
        with:
          filename: metrics.isocalendar.dark.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: dark
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - uses: lowlighter/metrics@latest
        name: Starred topics (dark)
        with:
          filename: metrics.topics.dark.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: dark
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred

      - uses: lowlighter/metrics@latest
        name: Recent activity (dark)
        with:
          filename: metrics.activity.dark.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: dark
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, push, fork, review, release

      - uses: lowlighter/metrics@latest
        name: Isometric calendar (light)
        with:
          filename: metrics.isocalendar.light.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: light
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - uses: lowlighter/metrics@latest
        name: Starred topics (light)
        with:
          filename: metrics.topics.light.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: light
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred

      - uses: lowlighter/metrics@latest
        name: Recent activity (light)
        with:
          filename: metrics.activity.light.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: light
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, push, fork, review, release

      - uses: lowlighter/metrics@latest
        name: Blog posts (dark)
        with:
          filename: metrics.blog.dark.svg
          token: NOT_NEEDED
          base: ""
          config_skin: dark
          plugin_rss: yes
          plugin_rss_source: https://time-friend.com/en/index.xml
          plugin_rss_limit: 10

      - uses: lowlighter/metrics@latest
        name: Blog posts (light)
        with:
          filename: metrics.blog.light.svg
          token: NOT_NEEDED
          base: ""
          config_skin: light
          plugin_rss: yes
          plugin_rss_source: https://time-friend.com/en/index.xml
          plugin_rss_limit: 10

      - uses: lowlighter/metrics@latest
        name: Languages (dark)
        with:
          filename: metrics.languages.dark.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: dark
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

      - uses: lowlighter/metrics@latest
        name: Languages (light)
        with:
          filename: metrics.languages.light.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: light
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

      - uses: lowlighter/metrics@latest
        name: Lines of code (dark)
        with:
          filename: metrics.lines.dark.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: dark
          plugin_lines: yes

      - uses: lowlighter/metrics@latest
        name: Lines of code (light)
        with:
          filename: metrics.lines.light.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: light
          plugin_lines: yes

      - uses: lowlighter/metrics@latest
        name: Coding habits (dark)
        with:
          filename: metrics.habits.dark.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: dark
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no

      - uses: lowlighter/metrics@latest
        name: Coding habits (light)
        with:
          filename: metrics.habits.light.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: light
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no

      - uses: lowlighter/metrics@latest
        name: Achievements (dark)
        with:
          filename: metrics.achievements.dark.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: dark
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0

      - uses: lowlighter/metrics@latest
        name: Achievements (light)
        with:
          filename: metrics.achievements.light.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: light
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0

      - uses: lowlighter/metrics@latest
        name: Notable contributions (dark)
        with:
          filename: metrics.notable.dark.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: dark
          plugin_notable: yes

      - uses: lowlighter/metrics@latest
        name: Notable contributions (light)
        with:
          filename: metrics.notable.light.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: light
          plugin_notable: yes

      - uses: lowlighter/metrics@latest
        name: Commit calendar (dark)
        with:
          filename: metrics.calendar.dark.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: dark
          plugin_calendar: yes
          plugin_calendar_limit: 0

      - uses: lowlighter/metrics@latest
        name: Commit calendar (light)
        with:
          filename: metrics.calendar.light.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: light
          plugin_calendar: yes
          plugin_calendar_limit: 0

      - uses: lowlighter/metrics@latest
        name: Featured repositories (dark)
        with:
          filename: metrics.repositories.dark.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: dark
          plugin_repositories: yes
          plugin_repositories_pinned: yes

      - uses: lowlighter/metrics@latest
        name: Featured repositories (light)
        with:
          filename: metrics.repositories.light.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_skin: light
          plugin_repositories: yes
          plugin_repositories_pinned: yes
